# Generated by Django 2.1.1 on 2018-10-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default='test', help_text='Short for title, used as the URL slug.', max_length=50, unique_for_date='post_date'),
            preserve_default=False,
        ),
    ]
