# Generated by Django 2.1.1 on 2018-12-04 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181012_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='blog.BlogAuthor'),
        ),
    ]
