# Generated by Django 2.1.1 on 2020-01-07 12:21

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181204_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=martor.models.MartorField(),
        ),
    ]
