# Generated by Django 3.0.2 on 2020-03-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200107_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content_xml',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(),
        ),
    ]
